config/routes.rb
Rails.application.routes.draw do
  post 'users/add' ,            to: 'users#create'
  post 'login',                 to: 'sessions#create'

  delete 'logout',              to: 'sessions#destroy'
  delete 'users/:id(.:format)', to: 'users#destroy'

  get 'login',                  to: 'sessions#new'
  get 'attendance/show'
  get 'users/index'
  get 'users/add'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace 'api' do
    namespace 'v1' do
      resources :admins
      resources :session
      resources :users
      resources :attendances


      post "/login"    => "session#create"
      delete "/logout" => "session#destroy"

      post 'attendance', to: 'attendances#create'
      get 'attendance',  to: 'attendances#index'

      end
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token :auth_token
  validates_uniqueness_of :studentnum
  has_many :attendances

  def invalidate_token
    self.update_columns(auth_token: nil)
  end

  def self.valid_login?(studentnum)
    user = find_by(studentnum: studentnum)
  end


  validates :studentnum, presence: true
  validates :firstname, presence: true
  validates :middlename, presence: true
  validates :lastname, presence: true

end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      def index
        users = User.order('created_at DESC');
        render json: {status: 'SUCCESS', message:'SIGNED UP', data:users},status: :ok
      end

      def show
        user = User.find(params[:id])
        render json:{status: 'SUCCESS', message:'LOADED PROFILE', data:user},status: :ok
      end

      def create
        user = User.new(user_params)

        if user.save
          render json: {status: 'SUCCESS', message:'PROFILE SAVED', data:user},status: :ok
          flash[:success] = "Welcome to the Sample App!"
        else
          render json: {status: 'ERROR', message:'PROFILE NOT SAVED', data:user.errors},status: :unprocessable_entity
          flash[:success] = "Welcome to the Sample App!"
        end
      end

      def destroy
        user = User.find(params[:id])
        user.destroy
        render json: {status: 'SUCCESS', message:'PROFILE DELETED', data:user},status: :ok
      end

      def update
        user = User.find(params[:id])
        if user.update_attributes(user_params)
          render json: {status: 'SUCCESS', message:'PROFILE UPDATED', data:user},status: :ok
        else
          render json: {status: 'ERROR', message:'PROFILE NOT UPDATED', data:user.errors},status: :unprocessable_entity
        end
      end

      private

      def user_params
        params.permit(:studentnum, :firstname, :middlename, :lastname)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :must_login

  def index
  end

  def create
    user = User.new(user_params)

      if user.save
        redirect_to users_index_path
      else
        render json: {status: 'ERROR', message:'PROFILE NOT SAVED', data:user.errors},status: :bad_request
      end
  end

  def destroy
      @user = User.find(params[:id])
      @user= user.destroy
    end

    private


    def user_params
      params.require(:user).permit(:studentnum, :firstname, :middlename, :lastname)
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/add.html.erb
<body>

    <title>Class Code</title>

  <center><b>ADD STUDENT</b></center>
  <div class="container">

  <%= form_for(:user , url: users_add_path) do |f| %>
  	<div class="form-group">
  	<%= f.label :studentnum %><br>
  	<%= f.text_field :studentnum, class: 'form-control col-xl-10 col-sm-6 mb-3' %>
  	</div>

  	<div class="form-group">
  		<%= f.label :firstname %><br>
  		<%= f.text_field :firstname,:cols => 30, :rows => 2 , style: 'resize:none;', class: 'form-control col-xl-10 col-sm-6 mb-3' %>
  	</div>

  	<div class="form-group">
  	<%= f.label :middlename %><br>
  	<%= f.text_field :middlename, class: 'form-control col-xl-10 col-sm-6 mb-3' %>
  	</div>

    <div class="form-group">
  	<%= f.label :lastname %><br>
  	<%= f.text_field :lastname, class: 'form-control col-xl-10 col-sm-6 mb-3' %>
  	</div>



  		<br><br><%= f.submit "Sign up", class: "col-xl-6 col-sm-6 mb-3 btn btn-primary btn-block mt-2 mx-2" %>
  		<% end %>



  </form>
</div>


  <style>
  body{
    background-color: #FFFACD;
    margin: auto;
  }
  center{
    font-size: 25pt;
    margin-top: 3%
  }
  button {
      background-color: #4CAF50;
      color: white;
      padding: 3% 3%;
      margin: 2% 0;
      border: none;
      cursor: pointer;
      width: 30%;
      opacity: 0.9;z
  }
  .container{
    margin-left: 35%;
    margin-top: 5%;
    width: 25%;
    height:40%;
    background-color:light green;
    box-shadow:2% 5% 5%;
    text-align:center;
    padding:5%;
    border: 2px black solid;
    background-color:  	#FFF0F5;
  }
  input[type=text]:focus {
      background-color: #ddd;
      outline: none;
  	   width: auto;
      padding: 2%;
      margin:auto;
      display: inline-block;
      border: none;
      background: #f1f1f1;
  }
  </style>
</body>

app/views/users/index.html.erb
<body>
    <title>Class Code</title>
  <center>
  <center><p>REGISTERED STUDENTS</p></center>
  <table>
  <tr>
    <th>Student Number</th>
    <th>First Name</th>
    <th>Middle Name</th>
    <th>Last Name</th>
    <th>Attendance</th>
  </tr>

  <% @users = User.all%>
  <% @users.each do |user| %>

  <tr>
      <td> <%=user.studentnum %> </td>
      <td> <%=user.firstname %> </td>
      <td><%=user.middlename %> </td>
      <td><%=user.lastname %> </td>
      <td><%= link_to "Show Attendance", attendance_show_path(attendance_show_url) %></td>


    </tr>
  </tr>
  <% end %>
  </table>
</center>

<center>
<%= link_to '<button type="button">Add</button>'.html_safe, users_add_path %>&nbsp;
<%= link_to '<button type="button">Logout</button>'.html_safe, logout_path, method: :delete %>
</center>
  <style>
  body{
    background-color: #FFFACD;
    margin: auto;
  }
  button {
      background-color: #4CAF50;
      color: white;
      padding: 1% 3%;
      margin: 2% 0;
      border: none;
      cursor: pointer;
      width: 15%;
      opacity: 0.9;z
  }

  table{
    width: 80%;
    padding: 3%;
    border: 1px solid black;
    margin-left:2%;
    height: inherit;
  }
  th{
    font-size: 15pt;
    text-align: left;
    border: 1px solid black;
  }
  td{
      border: 1px solid black;
      font-size: 12pt;
  }
  p{
    margin-top: 5%;
    font-size: 30pt;
  }
  </style>
</body>