config/routes.rb
Rails.application.routes.draw do
  post 'users/add' ,            to: 'users#create'
  post 'login',                 to: 'sessions#create'

  delete 'logout',              to: 'sessions#destroy'
  delete 'users/:id(.:format)', to: 'users#destroy'

  get 'login',                  to: 'sessions#new'
  get 'attendance/show'
  get 'users/index'
  get 'users/add'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace 'api' do
    namespace 'v1' do
      resources :admins
      resources :session
      resources :users
      resources :attendances


      post "/login"    => "session#create"
      delete "/logout" => "session#destroy"

      post 'attendance', to: 'attendances#create'
      get 'attendance',  to: 'attendances#index'

      end
  end


end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  validates :date, presence: true
  validates :attendance, presence: true

end

app/controllers/api/v1/attendances_controller.rb
module Api
  module V1
    class AttendancesController < ApplicationController
      def index
        attendances = Attendance.order('created_at DESC');
        render json: {status: 'SUCCESS', message:'SIGNED UP', data:attendances},status: :ok
      end

      def show
        attendance = Attendance.find(params[:id])
        render json: {status: 'SUCCESS', message:'LOADED PROFILE', data:attendance},status: :ok
      end

      def create
        if @current_user = User.find_by(studentnum: params[:studentnum])
          attendance = @current_user.attendances.new(attendance_params)
          if attendance.save
            render json: {status: 'SUCCESS', message:'PROFILE SAVED', data:attendance},status: :ok
          else
            render json: {status: 'ERROR', message:'PROFILE NOT SAVED', data:attendance.errors},status: :unprocessable_entity
          end
        end
      end

      def destroy
        attendance = Attendance.find(params[:id])
        attendance.destroy
        render json: {status: 'SUCCESS', message:'PROFILE DELETED', data:attendance},status: :ok
      end

      def update
        attendance = Attendance.find(params[:id])
        if attendance.update_attributes(attendance_params)
          render json: {status: 'SUCCESS', message:'PROFILE UPDATED', data:attendance},status: :ok
        else
          render json: {status: 'ERROR', message:'PROFILE NOT UPDATED', data:attendance.errors},status: :unprocessable_entity
        end
      end

      private

      def attendance_params
        params.permit(:user_id,:date, :attendance)
      end
    end
  end
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController

  def create
    attendance = Attendance.new(attendace_params)

      if attendace.save
        redirect_to attendance_show_path
      else
        render json: {status: 'ERROR', message:'PROFILE NOT SAVED', data:attendance.errors},status: :bad_request
      end
  end

  def destroy
      @attendance = Attendance.find(params[:id])
      @attendance = Attendance.destroy
    end

    private


    def attendance_params
      params.require(:attendance).permit(:date, :attendance)
    end


end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/views/attendance/show.html.erb
<body>
    <title>Class Code</title>
    <center>
  <center><p>REGISTERED STUDENTS</p></center>
  <table>
  <tr>
    <th>Date</th>
    <th>Attendance</th>
  </tr>

  <% @attendances = Attendance.all%>
  <% @attendances.each do |attendance| %>

  <tr>
      <td> <%=attendance.date %> </td>
      <td> <%=attendance.attendance %> </td>
  </tr>
  <% end %>
  </table>
  <%= link_to '<button type="button">Back</button>'.html_safe, users_index_path %>&nbsp;

</center>

  <style>
  body{
    background-color: #FFFACD;
    margin: auto;
  }
  button {
      background-color: #4CAF50;
      color: white;
      padding: 1% 3%;
      margin: 2% 0;
      border: none;
      cursor: pointer;
      width: 15%;
      opacity: 0.9;z
  }
  table{
    width: 80%;
    padding: 3%;
    border: 1px solid black;
    margin-left:2%;
    height: inherit;
  }
  th{
    font-size: 15pt;
    text-align: left;
    border: 1px solid black;
  }
  td{
      border: 1px solid black;
      font-size: 12pt;
  }
  p{
    margin-top: 5%;
    font-size: 30pt;
  }
  </style>
</body>